# Generated by Django 5.2.1 on 2025-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms_api', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=10),
        ),
    ]
