# Generated by Django 5.2.1 on 2025-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms_api', '0003_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
